import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import MainLayout from '../../../components/layouts/MainLayout'
import styles from '../../../styles/Home.module.css'
import { useRouter } from 'next/router'
import { Product } from '../../../components/products/product'
export default function SingleProduct({ product }) {
	return (
		<div>
			<Head>
				<title>{product.name} | luns shop</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='theme-color' content='#f6f2e5' />

				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div
				style={{
					padding: '1em',
				}}>
				<button type='text'>
					<Link href={`/`}>back</Link>
				</button>
			</div>
			<Product product={product} />
			<div
				style={{
					padding: '1em',
				}}>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
				labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
				laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
				voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
				non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</div>
		</div>
	)
}

SingleProduct.getLayout = function getLayout(page) {
	return <MainLayout>{page}</MainLayout>
}
export async function getServerSideProps(context) {
	// Fetch data from external API
	const id = context.params.id
	console.log(id)
	const dev = process.env.NODE_ENV !== 'production'

	const res = await fetch(
		`${dev ? 'http://' : 'https://'}${process.env.NEXT_PUBLIC_VERCEL_URL}/api/products/${id}`
	)

	const product = await res.json()

	// Pass data to the page via props
	return { props: { product } }
}
